conditions: v1
language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- 3.6
- 3.7

script: nosetests

jobs:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

  - stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)
    name: "Deploy"
    if: tag IS present
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        all_branches: true
        tags: true
      user: bosswissam
      password:
        secure: 
      distributions: clean --all sdist bdist_wheel
      skip_cleanup: true
      skip_upload_docs: true

cache:
  pip: true
